"""
mask_generation.py
-------------------
Helpers for turning raw band arrays (or pre-made band PNGs) into the
before/after water masks used by the change-detection stage.

This module wraps ndwi.py with a small amount of file-IO convenience so
pipeline.py stays readable. It does not know anything about the *source*
of the bands (synthetic sample vs. real Sentinel-2 raster) — that
distinction lives in sample_data.py today, and would live in a future
`satellite_loader.py` for real imagery.
"""

from __future__ import annotations

import os
from typing import Tuple

import numpy as np

from ndwi import calculate_ndwi, create_water_mask
from utils import save_binary_mask_png


def generate_mask_from_bands(
    green_band: np.ndarray,
    nir_band: np.ndarray,
    threshold: float = 0.0,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Full Green/NIR -> (ndwi, water_mask) convenience wrapper.

    Returns
    -------
    (ndwi, water_mask) : tuple of np.ndarray
    """
    ndwi = calculate_ndwi(green_band, nir_band)
    water_mask = create_water_mask(ndwi, threshold=threshold)
    return ndwi, water_mask


def save_mask(mask: np.ndarray, out_path: str) -> str:
    """Save a binary mask as a PNG and return the path."""
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    save_binary_mask_png(mask, out_path)
    return out_path


def load_bands(green_path: str, nir_path: str) -> Tuple[np.ndarray, np.ndarray]:
    """
    Load Green/NIR band images from disk.

    For the demo these are simple 8-bit PNGs generated by
    sample_data.py. For real satellite data, replace this function's
    body with a rasterio-based reader that opens the actual band files
    (e.g. Sentinel-2 B03/B08 JP2/TIFF) and also returns raster
    metadata (transform, resolution) so pixel_area_sqm can be derived
    instead of hard-coded in utils.PipelineConfig.
    """
    from utils import load_band_png

    green = load_band_png(green_path)
    nir = load_band_png(nir_path)
    return green, nir
